# Generated by Django 4.2.23 on 2025-11-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Addon Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, verbose_name='Full Name')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('timing', models.CharField(max_length=50, verbose_name='Timing')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('no_of_people', models.PositiveIntegerField(verbose_name='Number of People')),
                ('decoration', models.CharField(choices=[('with-decoration', 'With Decoration'), ('without-decoration', 'Without Decoration')], max_length=50, verbose_name='Decoration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birth.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='birth.eventbooking')),
            ],
        ),
    ]
