# Generated by Django 4.2.23 on 2025-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=50)),
            ],
        ),
    ]
