# Generated by Django 4.2.23 on 2025-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0002_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addons/'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingaddon',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='decoration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='fname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='no_of_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='timing',
            field=models.CharField(max_length=50),
        ),
    ]
