# Generated by Django 4.2.23 on 2025-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0003_remove_timeslot_slot_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('COD', 'Cash on Event')], default='Pending', max_length=20),
        ),
    ]
