# Generated by Django 4.2.23 on 2025-12-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0004_eventbooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='decoration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
